local_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../duckdb/warehouse.duckdb
      #path: C:/Users/sraikar/Documents/projects/APAC-DIA-Training-DE/duckdb/warehouse.duckdb
      threads: 4
      extensions:
        - delta
